#!/usr/bin/env python
# -*- coding: utf-8 -*-
__title__ = 'latinpigsay'
__license__ = 'MIT'
__author__ = 'Steven Cutting'
__author_email__ = 'steven.c.projects@gmail.com'
__created_on__ = '12/7/2014'

if __name__ == "__main__":
    from data.text import samples as sam
    from latinpigsay import generalfunctions as gfunc
    from tmp.experiments import expfunctions as expfunc

    from latinpigsay import latinpig as lp
    from latinpigsay import piggyprint as pp
    from tmp.experiments import exp

    import piglatin as pl

    import requests
    from itertools import izip

    import arrow
    import sys
    import re

    print
    sysinput = sys.stdin.read()
    print sysinput

    # translated = lp.translator(sysinput).returnstr
    translated = exp.translator(sysinput).returnstr
    pp.piggyprint(translated).printall

    translated = lp.translator(sysinput).returnstr
    pp.piggyprint(translated).printall

    print re.findall(r'(?:\S+)|(?:\s+)', sysinput)
